### ISSUE TITLE
Implementar acciones

### ISSUE THREAD

**Issue by mlafroce** [mlafroce/concurrentes#2]
1. Implementar las acciones simples:

    * Carta 10: "Buenos días señorita"
    * Carta 11: "Buenos noches caballero"
    * Carta 12: *venia militar*

2. Implementar puesta de mano al haber un "atrevido"

**Comment by mlafroce** [comment]
Para el punto 1 se me ocurre usar FIFOs, como todavía no lo vimos en la práctica, busqué un poco y encontré [esto](http://stackoverflow.com/questions/23433904/write-read-to-from-fifo-files-linux)

Creo que la posta es armar un fifo por jugador, y que el resto de los jugadores lean desde ahí. Por lo que veo el read es bloqueante, así que hay que ver como sobrepasar esto (si es que hay que leer los jugadores en paralelo).

**Comment by tbert12** [comment]
Hay 2 categorías de acciones.
Simple: No importa el orden
Acción de Mano: Importa la ultima mano que realizo la acción.

Se utiliza un array compartido donde se van "apilando" las acciones
